show databases;
create database shangjitwo;
use shangjitwo;
create table if not exists filminfo(
    actor text default null,
    date varchar(255)  default null,
    director varchar(255) default null,
    id int primary key ,
    language varchar(255) default null ,
    rate varchar(255) default null ,
    rating_num varchar(255) default null ,
    region varchar(255) default null ,
    runtime varchar(255) default null ,
    title varchar(255) default null ,
    type varchar(255) default null ,
    year varchar(255) default null ,
    is_cn boolean default null ,
    is_hk boolean default null ,
    is_tw boolean default null ,
    is_drama boolean default null ,
    is_comedy boolean default null,
    is_action boolean default null,
    is_romance boolean default null,
    is_scifi boolean default null,
    is_cartoon boolean default null,
    is_mystery boolean default null,
    is_thriller boolean default null,
    is_horror boolean default null,
    is_crime boolean default null,
    is_homosexua boolean default null,
    is_music boolean default null,
    is_musical boolean default null,
    is_biographical boolean default null,
    is_historical boolean default null,
    is_war boolean default null,
    is_western boolean default null,
    is_fantasy boolean default null,
    is_adventure boolean default null,
    is_disaster boolean default null,
    is_sowordsmen boolean default null,
    is_erotic boolean default null,
    is_best boolean default null,
    is_worst boolean default null
);